PR-Review
Dev-kunal/VideoLibrary-TechTube pull request #1
Opened 2021-04-29 09:01 UTC by Dev-kunal

Live preview of App (v1)
https://tech-tube.netlify.app/
initial features
1.Can create new playlist 
2.Can add videos to playlist
3.Can like/unlike a video

2021-04-29 14:47 UTC, Atishay-J reviewed
Looks good Kunal, just some style suggestions you can improve
1.  You should Increase the space between the bottom Nav and the main container,  on the mobile, the number of views of the last video, is not visible.
2.  Add a placeholder on the create new playlist input 
3. Add a default thumbnail image to the playlist, If I create a playlist but don't add any video in it, the UI breaks, it can be solved by adding a default image.

2021-04-29 16:13 UTC, amanpandey04 reviewed
Hey great work Kunal!
I had some style suggestions:
1. The thumbnails are good in PC view, but as soon as I go into mobile view, the size and alignment breaks. I would suggest use a uniform aspect ratio for the thumbnails, and try to look into the alignment in mobile and tablet view.
2. The Liked page is blank when there are no liked videos. Try showing a message like "You haven't liked any video yet".
3. There is no option to delete a playlist. If you're already working on it, that's awesome!
4. Inside playlists, try aligning the videos horizontally, so the user don't have to scroll down even if there are only 3 videos.

2021-05-01 13:05 UTC, im-rhlrvndrn requested changes

2021-05-01 13:05 UTC, imrhlrvndrn commented on src/Components/ActionModal.jsx
>      isInPlaylist(playlistToModify, video)
You can write the `isInPlaylist() on line 35` in a more effective way

```suggestion
 const isInPlaylist = ( playlistName, vidoeUrl ) => playlists.filter( ( listItem ) =>
        listItem.name === playlistName && listItem.itemsInPlaylist.includes( vidoeUrl )
      ).length;
```

This code will still check for both the conditions and return either `0` or `length in positive numbers => 1, 2, etc` and if the conditionals in this line would still work because `0` is treated as `false` and any positive number is treated as `true`

2021-05-01 13:05 UTC, imrhlrvndrn commented on src/Components/ActionModal.jsx
>  export const ActionModal = ({ setModalVisibility, isModalVisible, video }) => {
If all this Modal does is handle the Playlist functionalities then it'd be better to name it `PlaylistModal` because `ActionModal` is really confusing and it does explain the purpose of the Component

2021-05-01 13:05 UTC, imrhlrvndrn commented on src/Components/LikedVideos.jsx
>      return video;
Here too you can use ES6 syntax and write the function in one line

```suggestion
const getVideo = ( videoURL ) => videos.find(( video ) => video.url === videoURL );
```

2021-05-01 13:05 UTC, imrhlrvndrn commented on src/Components/Playlist.jsx
>  export const Playlist = () => {
On `line 11` if you do `+playlistId` it converts the id to `Number`

2021-05-01 13:05 UTC, imrhlrvndrn commented on src/Components/Playlist.jsx
>      return video;
Use ES6 syntax here

2021-05-01 13:05 UTC, imrhlrvndrn commented on src/Components/Playlists/Playlists.jsx
>  import { useNavigate } from "react-router-dom";
On `line 11` and `line 17` use ES6 syntax

2021-05-01 13:05 UTC, imrhlrvndrn commented on src/Components/Playlists/Playlists.jsx
>  import { useNavigate } from "react-router-dom";
On `line 28 - 29` if you want to do `console.log`'s to check the values at the point of time then take this approach instead of what you're doing currently

```suggestion
playlists.map( ( playlist ) => {
    console.log( playlist );
    return (...the JSX you want to return)
})
```

2021-05-01 13:05 UTC, imrhlrvndrn commented on src/Components/Watch/Watch.jsx
>  import { ActionModal } from "../ActionModal";
This will be renamed as `PlaylistModal`

2021-05-01 13:05 UTC, imrhlrvndrn commented on src/Components/Watch/Watch.jsx
>  export const Watch = () => {
`handlePlaylistListClick` can be renamed to `showPlaylistModal` and `handleLikeClick` to `likeVideo` OR something meaningful. Don't use the word `handle` in function names

2021-05-01 13:05 UTC, imrhlrvndrn commented on src/Context/VideoProvider/index.js
> +export const useVideo = () => {
use **ONE LINE** ES6 syntax here

2021-05-07 11:17 UTC, Dev-kunal commented on src/Context/VideoProvider/index.js
> +export const useVideo = () => {
Thank you very much @im-rhlrvndrn for this detailed code review and suggestions.
Got to learn some new things and tricks.
Made all the changes as you've suggested above.
Use Es6 syntax, modify function implementations into less code and change names of components and functions.

2021-05-07 11:23 UTC, Dev-kunal commented
Thank you very much @Atishay-J for the Review an UX suggestions.
Increase the space between Nav and the main container on mobile, to make last video detail visible
Add a placeholder on the create New playlist input
Add a default thumbnail image to the playlist, if it is empty

2021-05-07 11:28 UTC, Dev-kunal commented
Thank you @amanpandey04  for the Review an and pointing out some style issues and suggestions.
- fix the alignment of videos in the mobile view.
- add empty messages for liked video and empty playlist.
- align videos in playlist horizontally to to have better UX.

2021-08-11 04:27 UTC, merged